# Exercise 1.A NumPy: Manipulating Arrays
Cris Ramirez

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


----------------------
The first loop hits each row of the array, so it prints two arrays. 
The second loop goes one level deeper and hits each number, so it prints six values instead of two.

In [6]:
for x in arrA:
    for y in x:
        loop_result = x * 2
print(loop_result)
# This prints the whole row doubled, not just one number.
# loop_result keeps getting overwritten with x*2, after
# the loops finish we only see the last row t

[28 30 32]


## Joining and Stacking Arrays

In [7]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [8]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [9]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [10]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)
# This errors out. joined_array_1 is shape (4,3) and joined_array_2 is shape (2,6),
# so they don't match. np.stack needs both arrays to have the exact same shape.

ValueError: all input arrays must have the same shape

In [11]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [12]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)
# This breaks. joined_array_1 has 4 rows, arrA has 2 rows.
# To concat side by side on axis=1, both arrays need the same number of rows.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [16]:
h_stacked = np.hstack((arrA, arrA))   # stacks horizontally
print(h_stacked)

v_stacked = np.vstack((arrA, arrA))   # stacks vertically
print(v_stacked)

d_stacked = np.dstack((arrA, arrA))   # stacks depth-wise
print(d_stacked)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [17]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# Splits joined_array_1 into 2 arrays.
# joined_array_1 was shape (4,3), so we get two arrays of shape (2,3) each.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [18]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# Splits into 3 arrays. 4 rows don't divide evenly into 3,
# so NumPy gives us two arrays with 2 rows and one with 1 row.
# Shapes: (2,3), (1,3), (1,3

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [19]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [20]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [21]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [22]:
print(arrB)
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
