# Exercise 1.B NumPy Random
Cris Ramirez

In [1]:
import numpy as np

## Generating Random Numbers

In [3]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[ 2 16]


In [4]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[18  5]]


In [5]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.14297088]
 [0.5116447 ]]


In [6]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[33 65 25 27 37]
 [24 82 39 77 78]
 [53 84 59 36 83]
 [66 43 44 39 85]]


In [7]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.75561543 0.91333254 0.95266586 0.67185952 0.85765228]
 [0.40711168 0.19405841 0.19014008 0.06000244 0.55190834]
 [0.08452605 0.53594469 0.41444351 0.54224892 0.96282585]
 [0.8212697  0.86882716 0.27588832 0.65202275 0.57003822]]


## Generating Random Choices from an Array

In [15]:
students = np.array(['Aspenne', 'Chantal', 'Cris', 'Dania', 'Demy', 'Dimitri',
                     'Hamzah', 'Hana', 'Ivana', 'Jonathan', 'Jordan', 'Kasaiah'])
print(students)

['Aspenne' 'Chantal' 'Cris' 'Dania' 'Demy' 'Dimitri' 'Hamzah' 'Hana'
 'Ivana' 'Jonathan' 'Jordan' 'Kasaiah']


In [16]:
call_on = np.random.choice(students)
print(call_on)

Chantal


In [ ]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# Not a great way to assign breakout groups, np.random.choice samples WITH replacement,
# so the same person can show up multiple times while others get left out entirely.
# For real breakout groups you'd want to shuffle without replacement so everyone gets included once.

[['Hana' 'Kasaiah' 'Kasaiah' 'Kasaiah']
 ['Hamzah' 'Demy' 'Ivana' 'Ivana']
 ['Aspenne' 'Chantal' 'Aspenne' 'Hana']]


In [18]:
# Probabilities have to add up to 1.0
# Aspenne = 0 (never called on)
# Cris = 0.30 (favorite, obviously)
# Everyone else splits the remaining 0.70 evenly across 10 people = 0.07 each
probs = [0.0, 0.07, 0.30, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07]
call_on_weighted = np.random.choice(students, size=5, p=probs)
print(call_on_weighted)

['Jonathan' 'Cris' 'Cris' 'Hana' 'Hamzah']


## Generating a Normal Distribution

In [19]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 8.57214971  6.36745937 10.52948348 13.31801971  4.16471107]
 [10.53466422  5.31286449  2.39556745  1.8989503   8.35451319]
 [15.51857371  9.44764515  0.65544453  3.52865709 13.37818523]
 [ 5.68173676 11.02876847 18.64391944  9.50340464 15.21576791]]
