# Exercise 1.C Performing operations on arrays
Cris Ramirez

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

print('r_1:', r_1)
print('r_2:', r_2)
print('r_3:', r_3)
print('r_4:', r_4)
print('r_5:', r_5)

r_1: [14 15]
r_2: [[1 7]]
r_3: [[0.87064964]
 [0.05307109]]
r_4: [[87 96 61 94 53]
 [60 44 27 29 28]
 [68 49 63 67 99]
 [79 24 38 66 27]]
r_5: [[0.94855344 0.54081238 0.14631483 0.22503994 0.58655324]
 [0.6822478  0.92858024 0.76723039 0.82863618 0.71493081]
 [0.5539546  0.59218626 0.15285555 0.48949655 0.96973135]
 [0.70201443 0.59473428 0.97765001 0.88910814 0.70313243]]


## Permutations

In [9]:
print(r_4)

[[79 24 38 66 27]
 [87 96 61 94 53]
 [68 49 63 67 99]
 [60 44 27 29 28]]


In [10]:
np.random.shuffle(r_4)
print(r_4)

[[68 49 63 67 99]
 [87 96 61 94 53]
 [60 44 27 29 28]
 [79 24 38 66 27]]


Shuffle moves whole rows around, the individual numbers inside each row stay in the same order, but the rows themselves swap positions. It also modified r_4 directly instead of returning a new array.

In [11]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[68 49 63 67 99]
 [87 96 61 94 53]
 [60 44 27 29 28]
 [79 24 38 66 27]]
[[68 49 63 67 99]
 [87 96 61 94 53]
 [60 44 27 29 28]
 [79 24 38 66 27]]


Use shuffle when you want to scramble the original array in place and don't need to keep the old order. 

Use permutation when you want a shuffled copy but need the original array left alone.

## Mathematical Operations

In [12]:
print('r_1:', r_1, 'shape:', r_1.shape)
print('r_2:', r_2, 'shape:', r_2.shape)
result = np.add(r_1, r_2)
print('result:', result, 'shape:', result.shape)

r_1: [14 15] shape: (2,)
r_2: [[1 7]] shape: (1, 2)
result: [[15 22]] shape: (1, 2)


In [13]:
print('r_1:', r_1, 'shape:', r_1.shape)
print('r_3:', r_3, 'shape:', r_3.shape)
result = np.add(r_1, r_3)
print('result:', result, 'shape:', result.shape)

r_1: [14 15] shape: (2,)
r_3: [[0.87064964]
 [0.05307109]] shape: (2, 1)
result: [[14.87064964 15.87064964]
 [14.05307109 15.05307109]] shape: (2, 2)


In [14]:
print('r_2:', r_2, 'shape:', r_2.shape)
print('r_4:', r_4, 'shape:', r_4.shape)
result = np.add(r_2, r_4)
print('result:', result, 'shape:', result.shape)

r_2: [[1 7]] shape: (1, 2)
r_4: [[68 49 63 67 99]
 [87 96 61 94 53]
 [60 44 27 29 28]
 [79 24 38 66 27]] shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [15]:
print('r_1 shape:', r_1.shape)
print('r_4 shape:', r_4.shape)
# This errors. r_1 is (2,) and r_4 is (4,5).
# Aligning right: 2 vs 5, they're not equal and neither is 1, so broadcasting fails.
print(np.add(r_1, r_4))

r_1 shape: (2,)
r_4 shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [17]:
print('r_3 shape:', r_3.shape)
print('r_4 shape:', r_4.shape)
# This errors too. r_3 is (2,1) and r_4 is (4,5).
# Aligning right: 1 vs 5 (ok, one is 1), then 2 vs 4 (fail, not equal, neither is 1).
print(np.add(r_3, r_4))

r_3 shape: (2, 1)
r_4 shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [18]:
print(np.add(np.array([1]), r_4))
# Works! np.array([1]) is shape (1,). The single value 1 gets added to every element of r_4.

[[ 69  50  64  68 100]
 [ 88  97  62  95  54]
 [ 61  45  28  30  29]
 [ 80  25  39  67  28]]


In [19]:
print(np.add(np.array([[1]]), r_4))
# Also works. np.array([[1]]) is shape (1,1) — a 2D version of a single value.
# Same result as above, just with a different starting shape.

[[ 69  50  64  68 100]
 [ 88  97  62  95  54]
 [ 61  45  28  30  29]
 [ 80  25  39  67  28]]


In [20]:
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))
# Works! np.array([1,1,1,1,1]) is shape (5,) — matches the 5 columns of r_4.
# Each row of r_4 gets the row [1,1,1,1,1] added to it.

[[ 69  50  64  68 100]
 [ 88  97  62  95  54]
 [ 61  45  28  30  29]
 [ 80  25  39  67  28]]


In [ ]:
print(np.add(np.array([[1], [1]]), r_4))
# This errors. np.array([[1],[1]]) is shape (2,1).
# Aligning right: 1 vs 5, then 2 vs 4 fail.
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 