# Exercise 1.C Performing operations on arrays
Cris Ramirez

In [8]:
import numpy as np

## Sample Arrays

In [9]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

print('r_1:', r_1)
print('r_2:', r_2)
print('r_3:', r_3)
print('r_4:', r_4)
print('r_5:', r_5)

r_1: [19 16]
r_2: [[11 10]]
r_3: [[0.83130336]
 [0.56147544]]
r_4: [[73 62 33 32 44]
 [21 31 22 42 98]
 [76 88 97 64 84]
 [21 99 80 96 76]]
r_5: [[0.77833418 0.6814923  0.98788384 0.11651976 0.61925688]
 [0.21082751 0.8756147  0.27691343 0.48395081 0.98359301]
 [0.43368427 0.05918175 0.65105126 0.00157515 0.40861712]
 [0.40144335 0.92059109 0.74298477 0.01332372 0.85882191]]


## Permutations

In [10]:
print(r_4)

[[73 62 33 32 44]
 [21 31 22 42 98]
 [76 88 97 64 84]
 [21 99 80 96 76]]


In [11]:
np.random.shuffle(r_4)
print(r_4)

[[21 31 22 42 98]
 [21 99 80 96 76]
 [73 62 33 32 44]
 [76 88 97 64 84]]


Shuffle moves whole rows around, the individual numbers inside each row stay in the same order, but the rows themselves swap positions. It also modified r_4 directly instead of returning a new array.

In [12]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[76 88 97 64 84]
 [73 62 33 32 44]
 [21 31 22 42 98]
 [21 99 80 96 76]]
[[21 31 22 42 98]
 [21 99 80 96 76]
 [73 62 33 32 44]
 [76 88 97 64 84]]


Use shuffle when you want to scramble the original array in place and don't need to keep the old order. 

Use permutation when you want a shuffled copy but need the original array left alone.

## Mathematical Operations

In [13]:
print('r_1:', r_1, 'shape:', r_1.shape)
print('r_2:', r_2, 'shape:', r_2.shape)
result = np.add(r_1, r_2)
print('result:', result, 'shape:', result.shape)

r_1: [19 16] shape: (2,)
r_2: [[11 10]] shape: (1, 2)
result: [[30 26]] shape: (1, 2)


In [14]:
print('r_1:', r_1, 'shape:', r_1.shape)
print('r_3:', r_3, 'shape:', r_3.shape)
result = np.add(r_1, r_3)
print('result:', result, 'shape:', result.shape)

r_1: [19 16] shape: (2,)
r_3: [[0.83130336]
 [0.56147544]] shape: (2, 1)
result: [[19.83130336 16.83130336]
 [19.56147544 16.56147544]] shape: (2, 2)


In [15]:
print('r_2:', r_2, 'shape:', r_2.shape)
print('r_4:', r_4, 'shape:', r_4.shape)
result = np.add(r_2, r_4)
print('result:', result, 'shape:', result.shape)

r_2: [[11 10]] shape: (1, 2)
r_4: [[21 31 22 42 98]
 [21 99 80 96 76]
 [73 62 33 32 44]
 [76 88 97 64 84]] shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [16]:
print('r_1 shape:', r_1.shape)
print('r_4 shape:', r_4.shape)
# This errors. r_1 is (2,) and r_4 is (4,5).
# Aligning right: 2 vs 5, they're not equal and neither is 1, so broadcasting fails.
print(np.add(r_1, r_4))

r_1 shape: (2,)
r_4 shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [17]:
print('r_3 shape:', r_3.shape)
print('r_4 shape:', r_4.shape)
# This errors too. r_3 is (2,1) and r_4 is (4,5).
# Aligning right: 1 vs 5 (ok, one is 1), then 2 vs 4 (fail, not equal, neither is 1).
print(np.add(r_3, r_4))

r_3 shape: (2, 1)
r_4 shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [18]:
print(np.add(np.array([1]), r_4))
# Works! np.array([1]) is shape (1,). The single value 1 gets added to every element of r_4.

[[ 22  32  23  43  99]
 [ 22 100  81  97  77]
 [ 74  63  34  33  45]
 [ 77  89  98  65  85]]


In [19]:
print(np.add(np.array([[1]]), r_4))
# Also works. np.array([[1]]) is shape (1,1) — a 2D version of a single value.
# Same result as above, just with a different starting shape.

[[ 22  32  23  43  99]
 [ 22 100  81  97  77]
 [ 74  63  34  33  45]
 [ 77  89  98  65  85]]


In [20]:
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))
# Works! np.array([1,1,1,1,1]) is shape (5,) — matches the 5 columns of r_4.
# Each row of r_4 gets the row [1,1,1,1,1] added to it.

[[ 22  32  23  43  99]
 [ 22 100  81  97  77]
 [ 74  63  34  33  45]
 [ 77  89  98  65  85]]


In [21]:
print(np.add(np.array([[1], [1]]), r_4))
# This errors. np.array([[1],[1]]) is shape (2,1).
# Aligning right: 1 vs 5, then 2 vs 4 fail.
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

## How broadcasting works

When you add two arrays, numpy compares their shapes from right to left. Two dimensions can pair up if they're equal OR if one of them is 1. If a dimension is 1, numpy stretches it to match the bigger one. If both arrays clear all the dimension checks, the result takes the bigger shape from each pairing. If any dimension fails, you get a broadcasting error.

## Rounding

In [22]:
print(r_3)

[[0.83130336]
 [0.56147544]]


In [24]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [25]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [26]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [27]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [28]:
print(np.round(r_3, 2))

[[0.83]
 [0.56]]


## Cumulative Operations

In [29]:
print(r_4)

[[21 31 22 42 98]
 [21 99 80 96 76]
 [73 62 33 32 44]
 [76 88 97 64 84]]


In [31]:
print(np.sum(r_4))

1239


In [32]:
print(np.sum(r_4, axis=0))

[191 280 232 234 302]


In [33]:
print(np.sum(r_4, axis=1))

[214 372 244 409]


In [34]:
print(np.cumsum(r_4))

[  21   52   74  116  214  235  334  414  510  586  659  721  754  786
  830  906  994 1091 1155 1239]


In [35]:
print(np.cumsum(r_4, axis=0))

[[ 21  31  22  42  98]
 [ 42 130 102 138 174]
 [115 192 135 170 218]
 [191 280 232 234 302]]


## Grocery Problem

In [36]:
bag1 = np.array([2, 3, 4, 0]) 
bag2 = np.array([4, 0, 1, 2]) 

In [37]:
print('bag1:', bag1)
print('bag2:', bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [38]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)

In [39]:
print(f'The first bag contains {total_bag1} items, and the second bag contains {total_bag2} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [42]:
both_bags = np.vstack((bag1, bag2))
totals_by_category = np.sum(both_bags, axis=0)

In [43]:
print(f'There are {totals_by_category[0]} vegetables, {totals_by_category[1]} fruits, {totals_by_category[2]} boxes of snacks, and {totals_by_category[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [44]:
ali = np.array([5, 4, 6, 4, 2])
print('Ali:', ali)

Ali: [5 4 6 4 2]


In [45]:
ben = np.array([0, 5, 5, 3, 4])
print('Ben:', ben)

Ben: [0 5 5 3 4]


In [46]:
carla = np.array([3, 6, 0, 3, 4])
print('Carla:', carla)

Carla: [3 6 0 3 4]


In [47]:
all_knocks = np.vstack((ali, ben, carla))
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [48]:
per_person = np.sum(all_knocks, axis=1) 
grand_total = np.sum(all_knocks)

In [49]:
print(f'Ali: {per_person[0]}, Ben: {per_person[1]}, Carla: {per_person[2]}')
print(f'Group total: {grand_total} doors knocked.')

Ali: 21, Ben: 17, Carla: 16
Group total: 54 doors knocked.


In [51]:
daily_totals = np.sum(all_knocks, axis=0)
print('Daily totals:', daily_totals)

rolling_votes = np.cumsum(daily_totals) * 0.5
print('Rolling estimated votes by day:', rolling_votes)

Daily totals: [ 8 15 11 10 10]
Rolling estimated votes by day: [ 4.  11.5 17.  22.  27. ]
